name: 'packer'
description: 'Packer'
author: 'fergusn'
inputs: 
  template:
    description: 'Packer template'
runs:
  using: 'docker'
  image: 'docker://hashicorp/packer'
  args:
  - build
  - ${{ inputs.template }}
